### ISSUE TITLE
Hardcoded backend store code

### ISSUE THREAD

**Issue by ddonselaar** [experius/Magento-2-Module-Experius-MissingTranslations#13]
The backend store code is hardcoded in the js file. This should be generated by Magento.

https://github.com/experius/Magento-2-Module-Experius-MissingTranslations/blob/8b59aba228291e37c1161bbf414ffc994fc06e85/view/adminhtml/web/js/action/locale.js#L14

**Comment by lewisvoncken** [comment]
@ddonselaar 
This has been solved in the latest version 2.1.7
