### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by krukas** [experius/Magento-2-Module-Experius-MissingTranslations#4]
Errors during compilation:
	Experius\MissingTranslations\Controller\Adminhtml\Translation\Save
		Incorrect dependency in class Experius\MissingTranslations\Controller\Adminhtml\Translation\Save in /data/web/magento2/vendor/experius/module-missingtranslations/Controller/Adminhtml/Translation/Save.php

**Comment by lewisvoncken** [comment]
@krukas 
I can't reproduce the issue during di:compile.

**Comment by krukas** [comment]
This was for Magento 2.1: complete error:

`Total Errors Count: 1
Errors during compilation:
	Experius\MissingTranslations\Controller\Adminhtml\Translation\Save
		Incorrect dependency in class Experius\MissingTranslations\Controller\Adminhtml\Translation\Save in /data/web/magento2/vendor/experius/module-missingtranslations/Controller/Adminhtml/Translation/Save.php
\Magento\Framework\Locale\ResolverInterface already exists in context object
`
